### ISSUE TITLE
The performance of the Vit Tiny model is significantly reduced compared to the Vit  Small model

### ISSUE THREAD

**Issue by xuchunyuan** [BeSpontaneous/Proteus-pytorch#1]
![image](https://github.com/user-attachments/assets/760dae9e-47b7-4ed5-a4e8-d0dfcbaacd6c)
![image](https://github.com/user-attachments/assets/3ea48bb8-ef03-465f-b604-fc3bae15bb78)
I visualize the feature map and PCA , the result show that the performance of the Vit Tiny model is significantly reduced compared to the Vit  Small model
is this because the weight of model is too light to fit ?

**Comment by BeSpontaneous** [comment]
Hi, we have not visualized the results on the Tiny model but the inferior performance should be expected as the size is too small. Note that DINOv2 and SynCLR only show the visualization results of ViT-g and ViT-L, which are way larger than ViT-Tiny.
